# Generated by Django 4.2.7 on 2024-05-04 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_section_product_image_product_section_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Additional_Information',
            new_name='AdditionalInformation',
        ),
        migrations.RenameModel(
            old_name='Banner_area',
            new_name='BannerArea',
        ),
        migrations.RenameModel(
            old_name='Product_Image',
            new_name='ProductImage',
        ),
    ]
