# Generated by Django 5.0.4 on 2024-05-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='Image_url',
            field=models.URLField(max_length=500),
        ),
    ]
