# Generated by Django 5.0.4 on 2024-05-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_productimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='Image_url',
            field=models.CharField(max_length=500),
        ),
    ]
