# Generated by Django 5.0.4 on 2024-05-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='app_Product',
        ),
    ]
